# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/
#
#

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, class:qemu

windowrule = no_initial_focus on,match:class ^(net-runelite-client-RuneLite)$,match:title ^win(.*)$

windowrule {

name = world_of_warcraft

content = game

immediate = on

fullscreen = on

stay_focused = on

decorate = off

no_blur = on

border_size = 0

no_screen_share = on

no_dim = on

no_max_size = on

no_shadow = on

no_anim = on

workspace = 9

match:class = steam_app_0

} 

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf
